[package]
name = "xena"
version = "0.1"
lean_version = "master"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "5ad8020f67eb13896a41cc7691d072c9331b1f76"}
lean-protocol-support = {git = "https://github.com/GaloisInc/lean-protocol-support", rev = "cabfa3abedbdd6fdca6e2da6fbbf91a13ed48dda"}
